# Configurações do Spring Boot
spring.security.user.name=admin
spring.security.user.password=123456

# H2 database
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.hibernate.ddl-auto=create-drop


# Habilita o console web do H2
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Log do SQL
logging.level.org.hibernate.SQL=DEBUG

# Log dos valores dos parâmetros
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

